### ISSUE TITLE
IParser "prettyPrint" doesnt work 

### ISSUE THREAD

**Issue by matjop86** [hapifhir/hapi-fhir#2498] opened 2021-03-24 14:17 UTC
Even though the `xmlParser.setPrettyPrint(true)` option is set, it always says an error occurred in line 1.

**To Reproduce**
1. Set `ca.uhn.fhir.parser.IParser.setPrettyPrint(true)`
2. Run validation

**Expected behavior**
An information of particular line in which the error occurred (not always line 1).

**Screenshots**
![image](https://user-images.githubusercontent.com/81311981/112325483-0329b900-8cb4-11eb-8a99-bb0b1e490a18.png)

**Environment:**
 - HAPI FHIR Version: 5.3.0 (version for Java)
 - OS: Windows 10

**Comment by patrick-werner** [comment] 2021-03-24 14:35
Couldn't reproduce. Pretty print works:
````java
    FhirContext fhirContext = FhirContext.forR4();
    Patient patient = new Patient();
    patient.addName().addGiven("test");
    patient.setGender(AdministrativeGender.FEMALE);
    IParser jsonParser = fhirContext.newXmlParser().setPrettyPrint(true);
    System.out.println(jsonParser.encodeResourceToString(patient));
````
output:
````xml
<Patient xmlns="http://hl7.org/fhir">
   <name>
      <given value="test"/>
   </name>
   <gender value="female"/>
</Patient>
````

I think your issue is caused by the validator which can't point to a single line as the error cause.
Will close this issue

**Closed by patrick-werner** 2021-03-24 14:35 UTC
