### ISSUE TITLE
Potential race condition/conflict

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir#5288] opened 2023-09-07 09:23 UTC
We've experienced what looks like a potential race condition/conflict on HAPI FHIR 6.6.2.

From the data it looks like that two consecutive updates have been issued almost at the same time messing up the order in which version of the resource is the newest. The consequence of this leaves the resource in an inconsistent state where the resource cannot be updated afterwards.

The error message from the server is the following (when trying to update it afterwards):

"The operation has failed with a version constraint failure. This generally means that two clients/threads were trying to update the same resource at the same time, and this request was chosen as the failing request."

A dump of the resource history is as follows:

```

   "entry": [
        {
            "fullUrl": "https://xyz.cloud/fhir/Practitioner/416718",
            "resource": {
                "resourceType": "Practitioner",
                "id": "416718",
                "meta": {
                    "versionId": "3",
                    "lastUpdated": "2023-09-02T19:12:47.060+00:00",
                    "source": "http://xyz/admin"
                },
                "identifier": [
                    {
                        "extension": [
                            {
                                "url": "http://xyz/originatesFrom",
                                "valueString": "http://xyz"
                            },
                            {
                                "url": "http://xyz/verified",
                                "valueBoolean": true
                            }
                        ],
                        "system": "urn:oid:2.51.1.3",
                        "value": "123"
                    }
                ]
            },
            "request": {
                "method": "PUT",
                "url": "Practitioner/416718/_history/3"
            },
            "response": {
                "status": "200 OK",
                "etag": "W/\"3\""
            }
        },
        {
            "fullUrl": "https://xyz.cloud/fhir/Practitioner/416718",
            "resource": {
                "resourceType": "Practitioner",
                "id": "416718",
                "meta": {
                    "versionId": "4",
                    "lastUpdated": "2023-09-02T19:12:46.892+00:00",
                    "source": "http://xyz/admin"
                },
                "extension": [
                    {
                        "url": "http://xyz/fhir/StructureDefinition/practitioner-is-messageable",
                        "valueBoolean": false
                    }
                ],
                "identifier": [
                    {
                        "extension": [
                            {
                                "url": "http://xyz/originatesFrom",
                                "valueString": "http://xyz"
                            },
                            {
                                "url": "http://xyz/verified",
                                "valueBoolean": true
                            }
                        ],
                        "system": "urn:oid:2.51.1.3",
                        "value": "123"
                    }
                ]
            },
            "request": {
                "method": "PUT",
                "url": "Practitioner/416718/_history/4"
            },
            "response": {
                "status": "200 OK",
                "etag": "W/\"4\""
            }
        },
```

As can be seen, version 3 has a newer `lastUpdated` than version 4. Any modification on the resource afterwards produces the error message above.

**Comment by G-2-Z** [comment] 2023-09-07 13:01
We have a similar issue possibly related: https://github.com/hapifhir/hapi-fhir/issues/4843. Also see https://github.com/hapifhir/hapi-fhir/issues/4690.

**Comment by tadgh** [comment] 2023-09-07 17:52
Is this still replicable in master?

**Comment by jkiddo** [comment] 2023-09-07 17:56
We've seen it on 6.6.2 when the server comes under high load. We haven't had the chance yet to try out on either 6.8.2 or master.

**Comment by jamesagnew** [comment] 2023-09-08 11:46
This looks like the same issue as the two above - I'm going to close this as a duplicate of https://github.com/hapifhir/hapi-fhir/issues/4843, let's discuss over there.

**Closed by jamesagnew** 2023-09-08 11:46 UTC
