### ISSUE TITLE
Deleting a large valueset fails with transaction timeout because foreign key is not indexed

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/hapi-fhir#3316] opened 2022-01-19 12:29 UTC
**Describe the bug**
Deleting a large valueset fails with transaction timeout because foreign key is not indexed. 

**To Reproduce**
1. Create a valueset that includes a large codesystem, eg: 
`  "compose": {
    "include": [
      {
        "system": "http://snomed.info/sct"
      }
   }
`

2. Wait for terminology to expand the valueset
`.ValueSetConceptAccumulator     : Have pre-expanded ##### concepts in ValueSet`

3. Delete the valueset
` .BaseTermReadSvcImpl            : Deleting existing TermValueSet[12954] and its children...`
Transaction times out (after 60 minutes)

**Expected behavior**
The transaction should be much faster.
Investigation reveals the following SQL statement:
`
DELETE TRM_VALUESET_CONCEPT WHERE VALUESET_PID=?
`

The problem is that the table TRM_VALUESET_C_DESIGNATION has a FK constraint: 
`
CONSTRAINT fk_trm_valueset_concept_pid FOREIGN KEY (valueset_concept_pid)
        REFERENCES public.trm_valueset_concept (pid)
`
But there is no corresponding index and the FK requires that the database checks for detail rows when deleting master.
If I create an index:
`
CREATE INDEX idx_trmvaluesetcd_vsconceptpid
    ON public.trm_valueset_c_designation USING btree
    (valueset_concept_pid ASC NULLS LAST)
`
Then the transaction done in seconds (instead of hours).

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.4.0
 - OS: [e.g. iOS]: Linux/K8S

**Additional context**
See also: https://github.com/hapifhir/hapi-fhir/issues/2959

**Comment by jamesagnew** [comment] 2022-01-19 15:18
This appears to be a duplicate of #3108 - Please test on current snapshot builds and feel free to reopen if it is not fixed

**Comment by jamesagnew** [comment] 2022-01-20 12:34
@jmarchionatto

**Comment by jmarchionatto** [comment] 2022-01-20 14:46
Please add DB engine

**Comment by tyfoni-systematic** [comment] 2022-01-20 14:53
DB: Amazon Aurora PostgreSQL 10.14

**Comment by jmarchionatto** [comment] 2022-01-20 20:14
Definitely not a duplication of #3108, which fixed terminology deletion use case. Note that terminology deletion does not delete ValueSet(s).

**Comment by jmarchionatto** [comment] 2022-01-30 19:58
Can't reproduce the problem in my local postgres 13. (Complete SNOMED loaded, over 300K concepts ins ValueSet). Maybe because my trm_valueset_c_designation table is empty.
 
Could you please post the number of rows in your trm_valueset_c_designation table?

**Comment by tyfoni-systematic** [comment] 2022-01-31 07:09
`
select count(*), count(distinct valueset_pid), count(distinct valueset_concept_pid) from trm_valueset_c_designation;
209934	6791	209907

select count(*), count(distinct valueset_pid) from trm_valueset_concept;
432583	10840

select count(*), cnt from (select count(*) cnt , valueset_pid from trm_valueset_concept group by valueset_pid) x group by cnt order by cnt desc limit 10;
1	226740
1	114304
1	4475
1	3699
1	3116
1	2712
1	1920
1	1916
1	1749
1	1742
`

**Comment by jmarchionatto** [comment] 2022-02-07 21:41
Thank you @tyfoni-systematic

**Comment by jmarchionatto** [comment] 2022-02-23 18:55
Fixed by: https://github.com/hapifhir/hapi-fhir/pull/3416

**Closed by jmarchionatto** 2022-02-23 18:55 UTC
Labels: bug
