### ISSUE TITLE
Class too large: org/hl7/fhir/r5/formats/JsonParser

### ISSUE THREAD

**Issue by Athou** [hapifhir/hapi-fhir#3268] opened 2022-01-03 12:51 UTC
**Describe the bug**
We're using JaCoCO to measure code coverage.
In one of our unit tests, JaCoCo is printing the following stacktrace:

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/hl7/fhir/r5/formats/XmlParser.
        at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:5239)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:745)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:593)
        at org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.validate(ValidatorWrapper.java:158)
        at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validate(FhirInstanceValidator.java:235)
        at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:22)
        at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:45)
        at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:25)
        at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:221)
        at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:191)
```

Then another stacktrace, this time for `JsonParser`.

This is what the test does:
```java
@Test
void test() {
	FhirContext context = FhirContext.forR4();
	FhirValidator validator = context.newValidator();

	ValidationSupportChain validationSupportChain = new ValidationSupportChain(new DefaultProfileValidationSupport(context),
			new CommonCodeSystemsTerminologyService(context), new InMemoryTerminologyServerValidationSupport(context),
			new SnapshotGeneratingValidationSupport(context));
	CachingValidationSupport validationSupport = new CachingValidationSupport(validationSupportChain);
	validator.registerValidatorModule(new FhirInstanceValidator(validationSupport));

	AllergyIntolerance allergyIntolerance = new AllergyIntolerance();
	allergyIntolerance.setId("1");
	allergyIntolerance.setRecorder(new Reference(new Practitioner().setId("1")));

	ValidationResult validationResult = validator.validateWithResult(allergyIntolerance);
	Assertions.assertFalse(validationResult.isSuccessful(), validationResult.toString());

}
```

Our actual test is using `NpmPackageValidationSupport` as described [here](https://hapifhir.io/hapi-fhir/docs/validation/instance_validator.html#packages).

It seems that the `org.hl7.fhir.r5.formats.JsonParser` and `org.hl7.fhir.r5.formats.XmlParser` classes are too big to be instrumented by JaCoCo. Note that those classes belong to the `R5` version while our test is only using `R4`. The `R5` version seems to be instantiated from the `ourR5Context` static field of `VersionSpecificWorkerContextWrapper`.

**To Reproduce**
I have created a small project recreating the issue : 
1. `git clone https://github.com/Athou/hapi-jacoco-error.git`
2. `mvn test`

**Expected behavior**
The test should pass without errors printed in the console.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.6.1
 - OS: Windows

**Comment by rutixx** [comment] 2022-01-13 14:44
We are facing the same problem here.

We use R4, but the validator is internally uses R5.
HAPI FHIR version: 5.5.0
OS: Windows and Linux

**Comment by jamesagnew** [comment] 2022-01-13 15:49
HAPI's own build uses JaCoCo successfully - Are you using the current
release? Is there any difference you can spot between how you are using is
and how we use it in this repo?

**Comment by Athou** [comment] 2022-01-13 15:57
Yes we're using the latest version, 5.6.1.

Could you please point me to a test class using a custom ValidationSupportChain?

I also attached to the original post a really simple project reproducing the issue: https://github.com/Athou/hapi-jacoco-error

**Comment by Athou** [comment] 2022-01-13 16:06
I managed to simplify the test case further while still reproducing the issue:
```java
	@Test
	void test() {
		FhirContext context = FhirContext.forR4();
		FhirValidator validator = context.newValidator();
		validator.registerValidatorModule(new FhirInstanceValidator(new DefaultProfileValidationSupport(context)));

		AllergyIntolerance allergyIntolerance = new AllergyIntolerance();
		allergyIntolerance.setId("1");

		ValidationResult validationResult = validator.validateWithResult(allergyIntolerance);
		Assertions.assertFalse(validationResult.isSuccessful(), validationResult.toString());
	}
```

**Comment by rutixx** [comment] 2022-01-13 16:17
The problem is, that the test itself will succeed, but the code that is tested with it will not be treated as covered, because JaCoCo throws the exception above.

Mind, what @Athou has written exactly:

Expected behavior
The test should pass without errors **printed in the console**

So as far as I understand, the test always succeeds, but you have the exception of JaCoCo logged in the console.

**Comment by Athou** [comment] 2022-01-13 16:20
I now realize that the description of the issue was not precise enough, sorry :(

As @rutixx says, the test passes, but JaCoCo crashes and is not generating its report.

**Comment by rutixx** [comment] 2022-01-13 16:39
The class org.hl7.fhir.r5.formats.XmlParser is so big, that IntelliJ needed around one minute to open it.
It has 73685 lines of code!

**Comment by jamesagnew** [comment] 2022-01-13 18:20
Ah I see.

So I guess the next question is why it's getting used. That parser is
something Grahame uses in the FHIR IG tooling, but HAPI FHIR doesn't ever
actually use it afaik. At least when I run the test I linked to I don't see
it getting instantiated.

Are you able to provide a stack trace showing what's creating it?

Cheers,
James

**Comment by Athou** [comment] 2022-01-13 18:34
I've put breakpoints in the constructors of both parser classes and ran my unit test in debug mode but the test doesn't seem to instantiate the parser classes. I don't know how JaCoCo chooses what classes are instrumented.

I see this in the log however which is unexpected since R5 is not instantiated in my test:

    [main] INFO ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [R5]

A breakpoint on `ca.uhn.fhir.context.FhirContext.forR5()` shows the following stacktrace

```
Thread [main] (Suspended (breakpoint at line 1173 in FhirContext))	
	FhirContext.forR5() line: 1173	
	VersionSpecificWorkerContextWrapper.<clinit>() line: 58	
	FhirInstanceValidator.provideWorkerContext() line: 242	
	FhirInstanceValidator.validate(IValidationContext<?>) line: 223	
	FhirInstanceValidator(BaseValidatorBridge).doValidate(IValidationContext<?>) line: 22	
	FhirInstanceValidator(BaseValidatorBridge).validateResource(IValidationContext<IBaseResource>) line: 45	
	FhirInstanceValidator.validateResource(IValidationContext) line: 25	
	FhirValidator.validateWithResult(IBaseResource, ValidationOptions) line: 221	
	FhirValidator.validateWithResult(IBaseResource) line: 191	
	MyClassTest.test() line: 37	
```
Shouldn't `FhirInstanceValidator` use the context I supplied to validate the resources?

**Comment by jamesagnew** [comment] 2022-01-13 18:48
The R5 context is created automatically because we use the R5 validator to
validate all versions of FHIR (this avoids needing to maintain multiple
copies of the same codebase). This shouldn't cause any dependency on that
R5 JsonParser though.

This is a mystery...

**Comment by Athou** [comment] 2022-01-13 19:04
Ok, I understand now why you don't have the issue in this repo, it seems you're not using the default max metaspace size : https://github.com/hapifhir/hapi-fhir/blob/e6fd5c98077f4d8ca48d47bc840aec2c07b51709/pom.xml#L2841

Adding this to my pom.xml fixes the issue :)

			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.2</version>
				<configuration>
					<argLine>-XX:MaxMetaspaceSize=128M</argLine>
				</configuration>
			</plugin>

**Comment by jamesagnew** [comment] 2022-01-13 19:08
Interesting, I don't even remember why we added that but maybe this was the reason.

I'm going to close this since there is a workaround - If anyone wants to troubleshoot why we're even instrumenting that class in the first place I'm happy to reopen.

**Comment by Athou** [comment] 2022-01-14 07:44
I'm sorry I spoke too soon, setting `<argLine>-XX:MaxMetaspaceSize=128M</argLine>` is not correct as it seems to override the default argLine, disabling JaCoCo. The correct way is to set `<argLine>@{argLine} -XX:MaxMetaspaceSize=128M</argLine>` which causes the issue to happen again.

The good news is that I finally understand why you don't seem to see the error on this repo : `redirectTestOutputToFile` is set to `true` in the parent `pom.xml` and the error is not shown in the logs but found in a text file in `target/surefire-reports`.

To reproduce, execute `mvn clean package test -pl hapi-fhir-validation -Dtest=FhirInstanceValidatorR4Test#testValidateRawJsonResourceWithUnknownExtension` and find the JaCoCo error in `hapi-fhir-validation/target/surefire-reports/org.hl7.fhir.r4.validation.FhirInstanceValidatorR4Test-output.txt`.

**Comment by jamesagnew** [comment] 2022-01-22 00:24
This should be fixed now

**Closed** 2022-01-22 00:24 UTC
