### ISSUE TITLE
Incorrect Processing of Composite Search Parameters

### ISSUE THREAD

**Issue by juliangruendner** [hapifhir/hapi-fhir#2670] opened 2021-05-21 13:49 UTC
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

The server does not process composite Search Parameters correctly.

The expected result for composite parameters is that the server searches for the fulfilment of all composite search parameters in the same object (sub part) of the resource.

HAPI instead searches for any combination of attributes across objects (subparts) to fulfil the search criteria.

Example:

The following query:
http://hapi.fhir.org/baseR4/Observation?_pretty=true&component-code-value-quantity=http://loinc.org%7C8462-4$ge140&_count=500

returns as the very first entry:
http://hapi.fhir.org/baseR4/Observation/1721752

This observation should however not be found, as the diastolic blood pressure (8462-4) is not ge140

This error seems to apply to any composite parameter.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call Url: http://hapi.fhir.org/baseR4/Observation?_pretty=true&component-code-value-quantity=http://loinc.org%7C8462-4$ge140&_count=500

**Expected behaviour**
The expected result for composite parameters is that the server searches for the fulfilment of all composite search parameters in the same object (sub part) of the resource.

**Screenshots**

**Environment (please complete the following information):**
- http://hapi.fhir.org/baseR4/Observation

**Comment by alexanderkiel** [comment] 2021-05-21 20:25
This issue is a duplicate of #555 and can be closed.

**Closed** 2021-06-30 13:54 UTC
